### PR TITLE
[Project submission] After Me | Chainlink hackathon

### PR DESCRIPTION
**Pull request by EightRice**

### CODE REVIEW

**Comment by autonome** [comment]
Hi! In this PR you have accidentally deleted the template, and also put your project file in the `templates` directory. Can you update this PR or create a new one, which just creates your project file in the `projects` directory? Thanks!

**Comment by EightRice** [comment]
Changed the file in the `templates` folder back to what it was,
Added afterme.md to the `projects` folder.

**Comment by autonome** [comment]
Content looks great, thanks for updating. However, I need you to remove the change to the template file. It might be easier to just take the final project file and create a new PR that *only* adds that file in the `projects` directory.

**Comment by autonome** [comment]
Ah, you did in #498, so i merged that one and am closing this one.

**Pull request closed without merging**
