### PR TITLE
[Project Submission] NFT.Storage.

### PR DESCRIPTION
**Pull request by feliciss**
NFT.Storage: #576

### CODE REVIEW

**Comment by feliciss** [comment]
Updated docs for NFT.Storage: https://github.com/feliciss/nft.storage

**Comment by feliciss** [comment]
@autonome

**Comment by autonome** [comment]
Hi @feliciss , can you please rename your fork? It will be too confusing that you forked nft.storage and called it nft.storage. Please pick a name as you like.

**Comment by feliciss** [comment]
@autonome migrated this project to  #603

**Pull request closed without merging**
