### PR TITLE
Delete go-contribution-guidelines.md

### PR DESCRIPTION
**Pull request by lgierth**
This has been superseded by [contribute.md in go-ipfs](https://github.com/ipfs/go-ipfs/blob/master/contribute.md). We should look into making those guidelines visible to all go projects, but that can happen in the [devtools repo](https://github.com/ipfs/devtools).

### CODE REVIEW

**Comment by RichardLitt** [comment]
I brought that file here so that it would be visible to all projects. If you look at contribute.md in go-ipfs, it points to this file. I'm confused; how is it superseded?

**Comment by RichardLitt** [comment]
Needs rebase.

**Comment by RichardLitt** [comment]
@lgierth Perhaps I can help with this?

**Comment by lgierth** [comment]
This one and the contribute.md in go-ipfs have started to diverge. I propose we centralize this here, and have pointers from each go-* repo to here.

**Comment by lgierth** [comment]
> This one and the contribute.md in go-ipfs have started to diverge. I propose we centralize this here, and have pointers from each go-* repo to here.

cc @Kubuxu @hsanjuan @whyrusleeping

**Comment by hsanjuan** [comment]
SGTM, assuming that rules are written in a way that applies to all go-* and are not go-ipfs specific.

**Comment by diasdavid** [comment]
@lgierth seems like your [Proposal](https://github.com/ipfs/community/pull/202#issuecomment-278699869) and the title of this PR suggest different things. Maybe close the PR?

**Comment by diasdavid** [comment]
Follow on https://github.com/ipfs/community/issues/262

**Pull request closed without merging**
