### PR TITLE
Edited a section in README.md with quirky text

### PR DESCRIPTION
**Pull request by 7wikd**

### CODE REVIEW

**Comment by Stebalien** [comment]
What's the point of this change?

**Comment by 7wikd** [comment]
Oh, I was just attempting to appealing to the user by editing the text. I apologize if it doesn't seem useful.

**Comment by Stebalien** [comment]
That was an honest question. There's nothing especially wrong with the current statement and the new statement is a bit snarky.

**Comment by momack2** [comment]
Thanks for the feedback, but agree the previous text is more descriptive

**Pull request closed without merging**
