### PR TITLE
Added echo statements and .git check

### PR DESCRIPTION
**Pull request by RichardLitt**
This should make this script a bit easier to use.

### CODE REVIEW

**Comment by chriscool** [comment]
The commit I just pushed uses `git rev-parse --git-dir` and a `die()` function to be safer.

**Comment by RichardLitt** [comment]
@chriscool Looks awesome!

**Comment by chriscool** [comment]
@RichardLitt thanks!

**Comment by jbenet** [comment]
:+1: 

- we should have like a `ipfs-bin install <tool>`  (or `gx-bin`) that installs things like this script

**Comment by RichardLitt** [comment]
@jbenet Where can we open an issue about that? go-ipfs?

**Comment by jbenet** [comment]
@RichardLitt maybe notes repo

**Pull request merged**
