### PR TITLE
Added note about meta-non-code discussions

### PR DESCRIPTION
**Pull request by RichardLitt**
To make it clear this isn't for code topics. Result of talks in https://github.com/ipfs/community/issues/69.

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
typo at the end

**Comment by RichardLitt** [comment]
typo what typo

**Comment by Dignifiedquire** [comment]
no typo sorry just tired eyes :(

**Comment by RichardLitt** [comment]
haha there was one! I fixed it. Thanks for noticing. :)

**Comment by Dignifiedquire** [comment]
alright cool, I thought I was imagining things :D

**Comment by jbenet** [comment]
Thanks!

**Pull request merged**
