### PR TITLE
fix email link

### PR DESCRIPTION
**Pull request by KonradIT**
Fixed email with subject hyperlink, the spaces did not render the link correctly.

### CODE REVIEW

**Comment by Stebalien** [comment]
@flyingzumwalt do we have a better email for this now?

**Comment by flyingzumwalt** [comment]
We should probably remove that section entirely. For now, the more accurate info is

```
Protocol Labs occasionally is able to hire developers for part time or full time positions, to work on IPFS. If you are interested, check out [the job listings](http://protocol.ai/join). If you'd like to help in other ways, propose your ideas on the IPFS forums at https://discuss.ipfs.io.
```

**Comment by KonradIT** [comment]
@flyingzumwalt done!

**Comment by diasdavid** [comment]
Thank you all!

**Pull request merged**
