### PR TITLE
Add myrepos generator

### PR DESCRIPTION
**Pull request by lgierth**
Probably need to add a readme of some sort.

### CODE REVIEW

**Comment by RichardLitt** [comment]
100% needs to add a README, first. :)

**Comment by Kubuxu** [comment]
Yeah, it misses some repos in the gxed org, we should add them manually.

**Comment by lgierth** [comment]
This has been good to go for a while, sorry. It scans the ipfs, libp2p, multiformats, ipld, and gx organizations for repos starting `go-`, and also adds a few other repos.

The usual workflow is:
```sh
# init, also this is how to update when new repos are created
> cd $GOPATH/src/github.com/
> path/to/mkmrconfig.sh > .mrconfig
> mr checkout
> mr status

> mr -j 5 run git pull

> mr run cp `pwd`/ipfs/community/dev/tools/hooks/setup_commit_msg_hook.sh .git/hooks/

> mr run git commit -m "beep boop"
> mr run git push origin 
> mr run hub pull-request -m "Here's my PR"
```

So if you name interdependent branches accross repos the same, you can have something like topic workspaces: `mr run git checkout feat/something`

**Comment by lgierth** [comment]
For the near-term future, I propose an ipfs/devtools repo as a central place for tools, practices, questions, and discussions.

**Comment by RichardLitt** [comment]
> For the near-term future, I propose an ipfs/devtools repo as a central place for tools, practices, questions, and discussions.

This sounds good to me. Using community doesn't really work, and I would like to have a place to put standard-readme templates specific to IPFS and our other projects.

**Comment by RichardLitt** [comment]
Still needs this written up in a README, @lgierth

**Comment by lgierth** [comment]
Continuing this in https://github.com/ipfs/devtools

**Pull request closed without merging**
