### PR TITLE
Update the IPFS org JavaScript projects guidelines

### PR DESCRIPTION
**Pull request by diasdavid**
//cc @dignifiedquire @nginnever

### CODE REVIEW

**Comment by RichardLitt** [comment]
Who is this assigned to?

**Comment by dignifiedquire** [comment]
> Who is this assigned to?

To meeeee
giphy-5

**Comment by diasdavid** [comment]
@RichardLitt It is a WIP while we get `js-ipfs-api` with all the tooling set up so that we can use it as a project example.

Then we will need for your help in reviewing the document itself :)

**Comment by diasdavid** [comment]
@dignifiedquire opened a new PR to work on this that already incorporates the document proposal here, let's follow up there -> https://github.com/ipfs/community/pull/112

**Comment by diasdavid** [comment]
@RichardLitt I've just give me review on #f66ce1b, could you do a proof read so that we can merge this?

**Comment by RichardLitt** [comment]
Don't merge this yet. I'm going to do a PR against it.

**Comment by diasdavid** [comment]
@RichardLitt sounds good, I've updated it quite a bit too :)

**Comment by dignifiedquire** [comment]
@diasdavid @RichardLitt can we get this merged?

**Comment by dignifiedquire** [comment]
Need to add an `npmignore` note to avoid the issues we had with gitignore

**Comment by RichardLitt** [comment]
Needs to merge https://github.com/ipfs/community/pull/117 before merging into master. Discussion of #117 can happen on #117.

**Comment by RichardLitt** [comment]
Merged my edits. @dignifiedquire -- add an .npmignore section?

**Comment by diasdavid** [comment]
So, other than the `.npmignore`, we are good to merge?

**Comment by dignifiedquire** [comment]
Missing the notes about coveralls setup as well

**Comment by RichardLitt** [comment]
@dignifiedquire Can you add those?

**Comment by diasdavid** [comment]
all the ignores are there (thank you @dignifiedquire )

Are we ready to merge? :D

**Comment by RichardLitt** [comment]
Merged.

**Pull request merged**
