### PR TITLE
[WIP] Mid-Quarter Scoring and Re-Prioritizing

### PR DESCRIPTION
**Pull request by mikeal**
Some intitial scoring. @terichadbourne can you add your scoring in this branch?

I’m also working on re-prioritizing the Community WG in this PR. In this quarter, and next, we need to re-focus our priorities on either **new users** or **new contributors**. Additional PR’s to follow with new work items and priorities but, already, I’m cutting the automation at the bottom as it addresses long term contributors and is definitely not within this new priority scope.

### CODE REVIEW

**Comment by terichadbourne** [comment]
Here's where I'm at on these projects @mikeal. I just pushed a commit, but please let me know if you think I'm picking the wrong numbers based on this progress: 
- ProtoSchool roadmap: Opened an issue and Google Doc to start discussion but haven't had substantive progress. (0.1)
- ProtoSchool metrics: Got access to existing Google Analytics. Haven't yet added new tracking. How we do this will depend on whether we implement VuePress (0.1)
- ProtoSchool file sharing tutorial: Created an outline in the relevant GitHub issue of what should be covered in each lesson. Good start on designing UI for the file upload feature. Actual content of lessons not started.  (0.2)
- Publication articles: Started a GitHub discussion on potential topics and have ideas from a variety employees. Picked a topic that Dan of ProtoSchool Denver will write about. Need to select content/authors for remaining two articles. (0.2)

Are we going to do this exercise for our LabOS OKRs today as well?

**Comment by mikeal** [comment]
@terichadbourne I would rate the file sharing tutorial a bit higher, you’ve completed a lot of the code work already, I’d rank it a 0.3-0.4 but I’ll leave the final decision to you.

**Comment by terichadbourne** [comment]
@mikeal Thanks for the feedback. Bumped it to 0.3.

**Comment by mikeal** [comment]
@pkafei @terichadbourne we forgot to put projections in for end-of-quarter. Please add your respective scores, I tried to add a few based on recent conversations.

**Comment by terichadbourne** [comment]
@mikeal I updated my predicted EOQ scores, but would love to chat more about where I should focus my efforts since time is getting really short. Note that I struck through the publication goal that we decided to decommission given the lack of any pub to publish in and our lack of control over that project.

**Pull request merged**
