### PR TITLE
captain.log, aye, where is my grog

### PR DESCRIPTION
**Pull request by diasdavid**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Can you add some more description? Where was this talked about? Super cool idea.

**Comment by Dignifiedquire** [comment]
Would be nice to have `.md` as extension so it's properly rendered by github

**Comment by diasdavid** [comment]
@Dignifiedquire .md ✔️

@RichardLitt I started doing this back in the Summer of 2015, @jbenet asked me to document it during the last sprint for js-ipfs. I can add more description, any specifics you would like to see?

**Comment by RichardLitt** [comment]
@diasdavid I edited it: check out this version: https://gist.github.com/RichardLitt/5dfbe106eb87bf438291

**Comment by diasdavid** [comment]
@RichardLitt LGTM :) wanna commit that to this PR?

**Comment by RichardLitt** [comment]
Done. Added another line about location, too. @diasdavid thoughts?

**Comment by diasdavid** [comment]
LGTM :) merging

**Pull request merged**
