### PR TITLE
Standardized Readme, added License

### PR DESCRIPTION
**Pull request by RichardLitt**
See https://github.com/ipfs/community/issues/124#issuecomment-226484452

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Needs rebase

**Comment by RichardLitt** [comment]
Rebased.

**Comment by RichardLitt** [comment]
@dignifiedquire Is this good, otherwise?

**Comment by dignifiedquire** [comment]
@RichardLitt sorry for the delay lets get this in 👍

**Comment by diasdavid** [comment]
thank you :)

**Pull request merged**
