### PR TITLE
[Project Submission] Community Showcase Submission

### PR DESCRIPTION
**Pull request by Josiassejod1**

### CODE REVIEW

**Comment by Josiassejod1** [comment]
@TheDiscordian can you help push this through?

**Review by mishmosh — COMMENTED** [review]
Hello and thank you for the submission! Under "team size" you listed that you worked on this project solo. Under "team members" however, 3 people are listed. Can you clarify please? The rest of this PR looks great.

**Comment by Josiassejod1** [comment]
@mishmosh just some copy and paste mixup, I forgot to remove it from the template

**Review by mishmosh — APPROVED** [review]

**Comment by Josiassejod1** [comment]
March 1, 2021

I have just been notified that I will be receiving a microgrant for my submission. I am excited. I have begun looking to contract out a UX / UI Designer in order to help me build out new mocks for front-end. I need to generate new requirements in order to make sure I have all the features that I want in the v1.

I will also be getting some assets made for the NFT when the lots are generated.

**Comment by Josiassejod1** [comment]
March 8:

Working with a designer to scope on direction of the application

Got some direction from a founder that I know
Got some direction from a  employee who works at a VC on a pitch deck

Met with Senior Architect on direction of the backend design

**Comment by mishmosh** [comment]
Cool!

**Comment by Josiassejod1** [comment]
When I did the hackathon, I used a json payload for the houses so I can iterate fast during the Eth Global Hackathon.

I had began setting up firebase as a backend because that I was familiar with but I realized I would probably be reinventing the wheel with a lot of the solutions in firebase. Therefore I am opting to use Moralis, a "firebase for crypto" as they say in their docs in order to get the ease of the web2 auth and web3 token management that I don't really want to deal with managing.

**Comment by Josiassejod1** [comment]
So this week i started a new repo. The Hackathon repo I had was a bit too messy so I started from scratch using Moralis.

Things i need to think through is KYC and validation that a user really owns a property

**Comment by Josiassejod1** [comment]
Found a list of APIs for real estate that can prove very useful
https://gist.github.com/patpohler/36c731113fd113418c0806f62cbb9e30

**Comment by Josiassejod1** [comment]
So I have been creating use case diagrams of all the users for the platform 

The designer will start breaking ground on the design so we can start implementing the visual

**Comment by Josiassejod1** [comment]
I didn't want to make a mistake of implementing without thinking through features so I decided to put all my use cases down for all the users on the platform 

After that I will have a designer that will help me flesh out the designs and make them come to Loren

**Comment by Josiassejod1** [comment]
Started working on the v2 app will upload to vercel so that i can have demo link

**Comment by Josiassejod1** [comment]
![Uploading 163751759...]
![Uploading 163751910...]

Got some isometric images off Fiverr and bought a domain

**Comment by jenks-guo-filecoin** [comment]
@Josiassejod1 the images didn't seem to finish loading to GitHub.com. 😃

**Comment by Josiassejod1** [comment]
Got a designer working on figma mocks now too

**Comment by Josiassejod1** [comment]
Got the dev branch up here, [realty-dapp-v2-gkpiolvat-josiassejod1.vercel.app](https://vercel.com/josiassejod1/realty-dapp-v2/8zLWm1nDua5S6u877k24j3JuidnC)

**Comment by Josiassejod1** [comment]
image

Paid a designer for their services

**Comment by Josiassejod1** [comment]
Haven't left an update in a while, I really have just been building the component library out,

**Pull request merged**
