### PR TITLE
[Project Submission] IPFSfB

### PR DESCRIPTION
**Pull request by feliciss**
IPFSfB: https://github.com/ipfs/community/discussions/574

### CODE REVIEW

**Comment by autonome** [comment]
Hi @feliciss, a couple of questions:

1. These projects are not very clear in what they do. The first one appears to be a fork of an IBM project, but does not say how it is different. The second one has no information in the README about what it actually is or does.
2. Please submit PRs for *one* project at a team, it makes it much easier to evaluate.

**Comment by feliciss** [comment]
> 2\. submit PRs for _one_ project at a team

1. Will update the README both in the separated repos. The original author of that IBM project is me, and I'm not using that repo for potential company policies to enforce Apache License, so I created another forked repo to use the MIT license.
2. What does 'one project at a team' mean? Am I supposed to be creating a new organization at Github and migrate these projects to that org, or submitting PRs separately for each project?

**Comment by feliciss** [comment]
Updated docs for IPFSfB: https://github.com/feliciss/ipfsfb

**Comment by feliciss** [comment]
Updated docs for NFT.Storage: https://github.com/feliciss/nft.storage

**Comment by feliciss** [comment]
Migrated NFT.Storage project to #587 
This thread is now only for IPFSfB.

**Comment by feliciss** [comment]
@autonome

**Comment by autonome** [comment]
Thanks for fixing! Apologies, I meant "at a time", not "at a team" - thanks for splitting them up into two PRs.

**Pull request merged**
