### PR TITLE
Edited amending-commits doc. Added a TOC, improved language

### PR DESCRIPTION
**Pull request by RichardLitt**

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
I suggest running the content through http://www.hemingwayapp.com/ to ensure that the whole text is easy to read and understand and improve the language based on that.

**Comment by RichardLitt** [comment]
@Dignifiedquire I disagree. I ran it through there. I found the suggestions were either linguistically not valid (it mistakes any use of a modal for a passive verb), wrongly marked as too long due to links, or suggested words that don't fit the coding niche. I think we could make something better - something like https://github.com/btford/write-good - but I think that hemingway app for now doesn't work well for markdown readmes. :/ I could see how it would be useful for more general texts, though.

**Comment by Dignifiedquire** [comment]
@RichardLitt interesting. I haven't used it for purely technical texts so it might very well be that it's too weak there. Write-good looks quite promising, but there is much room for improvements with all these tools.

**Comment by RichardLitt** [comment]
@Dignifiedquire was there a reason you suggested that, or does this look good otherwise?

**Comment by Dignifiedquire** [comment]
@RichardLitt no looks good, was just reminded about it when reading the commit

**Pull request merged**
