### PR TITLE
Community Roadmap

### PR DESCRIPTION
**Pull request by mikeal**
After a lot of planning with the rest of the IPFS project the short terms goals and timeline for the Community WG have been defined.

I've adapted our prior roadmap into a format that is much more understandable by people who haven't been involved in the IPFS planning process. Terms like "KPI" have been remove and replaced with more descriptive language like "Success Criteria." 

I've also made sure that each project has at least one link someone can go to if they are interested in contributing to the project at what ever stage it is at.

### CODE REVIEW

**Comment by terichadbourne** [comment]
@mikeal I like the way you've linked out to issue folks can contribute to. 

A few suggestions/questions... 

You've linked to the issue for the 1.0 release, but we are planning to close that and instead just use the milestone feature of GH. I'm thinking it would be more relevant to link to: https://github.com/ipfs-shipyard/proto.school/milestone/1
(I've gone into that old release tracking issue and added links to where people can find the various issues and the list of issues that fall within the milestone, in case anyone still makes their way to that page. )

You've linked to a list of team responsibilities at https://github.com/mikeal/team-mgmt/blob/master/TEAM_STRUCTURES.md#community which are actually contested right now per the convo in the Google Doc roadmap file. Do you want to ignore this problem for now? 

Under ProtoSchool measurements you include "Average % completeness of each workshop." Just confirming that would be based on number of lessons complete within each workshop? If we aren't making users create accounts I have no idea how we would gather up the stats on how far along each user is in their lessons, even though that info would be available to that user on a particular browser. (And note that if they use multiple browsers they'll get double counted.) Is this something that will be on my plate or the plate of a new metrics person? 

I also don't currently know how to capture "Unique site visitors per month." but I presume there's some service that will make that one much simpler. 

I would recommend changing "like" to "similar to" in the sentence "The Community WG is planning to create starter kits which help people build on top of IPFS right away, like Truffle Boxes." "Like" is often used colloquially to mean "including," and my impression is that Truffle Boxes are a third party thing we'll take inspiration from, not actually create. (cc @pkafei)

We need hyphenation or different phrasing for "Use Case Specific Quickstarts" to make it both grammatical and unambigous. It's too easy to read "use" as a command here.  "Use-Case-Specific Quickstarts" is super hypheny but unambiguous (think "state-of-the-art technology"). I like it better than "Quickstarts Based on Use Cases," which would eliminate both the ambiguity and the grammar issue. 

Bullets throughout shouldn't end in periods. I'm happy to go through and fix this myself if you'd like. 

Do we need to make edits to README.md (or elsewhere) to include a link to this ROADMAP.md file?

**Comment by terichadbourne** [comment]
@mikeal Note that the OKR Molly is proposing in the generic IPFS roadmap is different than the one you're proposing here. I copied you on a comment to her about that here: https://docs.google.com/document/d/13_4_23Jrth7HBZ1QD6ezJaLRYCHN32xJLA5c0z3IOkc/edit?disco=AAAACXHb9lc

And she has in there a goal for ProtoSchool getting a certain monthly attendance at IPFS workshops (see https://docs.google.com/document/d/13_4_23Jrth7HBZ1QD6ezJaLRYCHN32xJLA5c0z3IOkc/edit?disco=AAAACXc_KCc) I'm not clear on whether that's meant to be community-hosted meetups, stuff we plan, stuff that belongs to the events team, etc., so I don't know who's responsible for that OKR.

**Comment by mikeal** [comment]
> You've linked to a list of team responsibilities at mikeal/team-mgmt:TEAM_STRUCTURES.md@master#community which are actually contested right now per the convo in the Google Doc roadmap file. Do you want to ignore this problem for now?

It's not contested what the responsibilities are, there's a lack of alignment about how the roadmap should best reflect the responsibilities and 2019 ORKs. The roadmap is our *current* workload with existing resources. 2019 OKRs will cover what we *want* to cover given more resources, and that will include the full scope of the WG.

> Under ProtoSchool measurements you include "Average % completeness of each workshop." Just confirming that would be based on number of lessons complete within each workshop? If we aren't making users create accounts I have no idea how we would gather up the stats on how far along each user is in their lessons, even though that info would be available to that user on a particular browser. (And note that if they use multiple browsers they'll get double counted.) Is this something that will be on my plate or the plate of a new metrics person?
> I also don't currently know how to capture "Unique site visitors per month." but I presume there's some service that will make that one much simpler.

We can actually capture all of these entirely with Google Analytic :)

How we score this is up for debate (total completions vs cumulative completions based on % complete), we'll work on that and iterate once we are capturing the metrics.

> I would recommend changing "like" to "similar to" in the sentence "The Community WG is planning to create starter kits which help people build on top of IPFS right away, like Truffle Boxes." "Like" is often used colloquially to mean "including," and my impression is that Truffle Boxes are a third party thing we'll take inspiration from, not actually create. (cc @pkafei)

We may actually use Truffle Boxes and not do our own thing. Still, "like" is not properly descriptive. I'll change it to whatever @pkafei thinks is accurate since she's done much more in this area.

**Comment by mikeal** [comment]
> Bullets throughout shouldn't end in periods. I'm happy to go through and fix this myself if you'd like.

Please do :)

**Comment by mikeal** [comment]
> Do we need to make edits to README.md (or elsewhere) to include a link to this ROADMAP.md file?

The README needs a massive update. I'll take this on after this lands.

**Comment by mikeal** [comment]
@terichadbourne RE: reconciling OKR's from IPFS with this roadmap.

The Google doc is taking so long to load that the deep links to comments aren't working so I'm having a hard time finding the exact metrics.

Let's make sure that the OKR's in the IPFS Roadmap are broad enough that we have the flexibility to score a few different metrics once we actually start measuring things. 

Similarly, there is a goal in the Events OKRs around "new ProtoSchool chapters created" that will need to make it in once those are finalized.

**Comment by pkafei** [comment]
>I would recommend changing "like" to "similar to" in the sentence "The Community WG is planning to create starter kits which help people build on top of IPFS right away, like Truffle Boxes." "Like" is often used colloquially to mean "including," and my impression is that Truffle Boxes are a third party thing we'll take inspiration from, not actually create

According [the  Cambridge dictionary](https://dictionary.cambridge.org/us/dictionary/english/like), "like" when used as a preposition means "similar to", but I can see where "like" can also be interpreted as meaning "the same". I'm ok with scrapping the word "like" and replacing it with a word that causes slightly less confusion.

As for the Truffle Boxes, I plan on creating boiler plate code that deals with common [IPFS use case](https://github.com/ipfs/community/blob/439b665715735e5730ffa38fb7e1055e78059b54/ROADMAP.md#Use-Case-Specific-Quickstarts). The user can build an app based on the skeleton code provided- it will work in a similar manner to [Yeoman Generator](http://yeoman.io/generators/), or [Truffle Boxes](https://truffleframework.com/boxes). This quarter I'll create a list of interesting IPFS hello world apps, and Q1 2019 I will start writing the IPFS boiler plate code for these applications.

**Pull request merged**
