### PR TITLE
Add ipfs/reading-list to about section

### PR DESCRIPTION
**Pull request by RichardLitt**
See ipfs/community#164

### CODE REVIEW

**Comment by flyingzumwalt** [comment]
I think this should include all of the bibliography lists (awesome, papers, and reading-list). Do you agree?

**Comment by RichardLitt** [comment]
Awesome, yes. I'm not sure about papers yet. To be honest, the docs website points to those repos. Perhaps we should overhaul that, instead of having three or four places; have one.

**Comment by flyingzumwalt** [comment]
Are you suggesting that the conclusion from ipfs/community#164, keeping all this info in 3 different repos, is wrong and proposing that they should be consolidated into one repository?

**Comment by RichardLitt** [comment]
I was thinking more about one reference point for where to look for other repos; having it in ipfs.io/docs makes sense, because the website is a huge entrypoint for the organization, especially for those not used to GitHub. Having a link to docs repos in ipfs/ipfs makes sense, because we have made that kind of like an entry point into the GitHub organization - it's where you go to find out about community, pm, and the like. We should link to ipfs/ipfs from all of the other GitHub repos, most likely, because right now we don't. But I'm not sure that we should duplicate these two lists in ipfs/community. I added this here because it seemed like the right place for it, but I'm not too happy with that section of this README, anyway. Overhauling it would be A+. 

Regarding consolidation: I'm not sure why there needs to be two different repos for papers, it can be confusing. I know why awesome-ipfs exists; I made it, and it highlights things that are, well, _awesome_. Not all papers are or will be, and not all papers belong there - but having ipfs/papers and ipfs/reading-list will get confusing.

**Comment by flyingzumwalt** [comment]
👍 to Making a central place for people to find out where stuff is and get up-to-date links

Please put your suggestions about consolidation into #164 since we're already discussing the topic there. I agree that consolidating all papers in one place makes more sense than keeping them split up.

**Comment by jbenet** [comment]
Worth mentioning: The goal for reading-list repo was a bibliography for us
to read, i.e. Other people's papers in relevant fields. Not neceassarily
papers about ipfs. I'm fine keeping this all in one repo,. Just want to
mention that use case

**Pull request merged**
