### PR TITLE
Idea: IPFS Community Events

### PR DESCRIPTION
**Pull request by diasdavid**
Goal of logging all the events that happened or that are scheduled by the IPFS community, so that people can have track of where to find more about IPFS in person.

The list is not complete yet, please add all that you come to your head

We can also grab this list and feed it to the website to show what are the next events, similar to what Nodeschool does

### CODE REVIEW

**Comment by lgierth** [comment]
We also did a meetup at c-base/berlin on august 27 -- do battlemesh and camp count? They weren't "scheduled by the IPFS community" (container.camp and dtn neither), but certainly events to advertise on the website in the future.

**Comment by diasdavid** [comment]
@lgierth my rule of thumb would be "where the community can find people talking about IPFS" :)

**Comment by lgierth** [comment]
> my rule of thumb would be "where the community can find people talking about IPFS" :)

SGTM :+1:

**Comment by RichardLitt** [comment]
This lgtm! We should also add these to the Calendar.

**Comment by jesseclay** [comment]
Also, advertising events on meeting specific sites, such as meetup.com could be useful to see RSVP lists & attendance counts.

**Comment by RichardLitt** [comment]
@lgierth Want to add those events?
@diasdavid should we add arcticjs?

**Comment by lgierth** [comment]
@RichardLitt yeah let's merge and go from there. I'll add c-base/battlemesh/camp/32c3.

Definitely add arcticjs haha :)

**Comment by RichardLitt** [comment]
@lgierth Ok, add away!

**Comment by lgierth** [comment]
done \o/

**Pull request merged**
